### Ironsworn
#
# Use this table to inspire a discovery, event, character goal, or situation. A roll
# on this table can be combined with a Theme (see below) to provide an action
# and a subject.
action_ironsworn = {
    1: 'Scheme',
    2: 'Clash',
    3: 'Weaken',
    4: 'Initiate',
    5: 'Create',
    6: 'Swear',
    7: 'Avenge',
    8: 'Guard',
    9: 'Defeat',
    10: 'Control',
    11: 'Break',
    12: 'Risk',
    13: 'Surrender',
    14: 'Inspect',
    15: 'Raid',
    16: 'Evade',
    17: 'Assault',
    18: 'Deflect',
    19: 'Threaten',
    20: 'Attack',
    21: 'Leave',
    22: 'Preserve',
    23: 'Manipulate',
    24: 'Remove',
    25: 'Eliminate',
    26: 'Withdraw',
    27: 'Abandon',
    28: 'Investigate',
    29: 'Hold',
    30: 'Focus',
    31: 'Uncover',
    32: 'Breach',
    33: 'Aid',
    34: 'Uphold',
    35: 'Falter',
    36: 'Suppress',
    37: 'Hunt',
    38: 'Share',
    39: 'Destroy',
    40: 'Avoid',
    41: 'Reject',
    42: 'Demand',
    43: 'Explore',
    44: 'Bolster',
    45: 'Seize',
    46: 'Mourn',
    47: 'Reveal',
    48: 'Gather',
    49: 'Defy',
    50: 'Transform',
    51: 'Persevere',
    52: 'Serve',
    53: 'Begin',
    54: 'Move',
    55: 'Coordinate',
    56: 'Resist',
    57: 'Await',
    58: 'Impress',
    59: 'Take',
    60: 'Oppose',
    61: 'Capture',
    62: 'Overwhelm',
    63: 'Challenge',
    64: 'Acquire',
    65: 'Protect',
    66: 'Finish',
    67: 'Strengthen',
    68: 'Restore',
    69: 'Advance',
    70: 'Command',
    71: 'Refuse',
    72: 'Find',
    73: 'Deliver',
    74: 'Hide',
    75: 'Fortify',
    76: 'Betray',
    77: 'Secure',
    78: 'Arrive',
    79: 'Affect',
    80: 'Change',
    81: 'Defend',
    82: 'Debate',
    83: 'Support',
    84: 'Follow',
    85: 'Construct',
    86: 'Locate',
    87: 'Endure',
    88: 'Release',
    89: 'Lose',
    90: 'Reduce',
    91: 'Escalate',
    92: 'Distract',
    93: 'Journey',
    94: 'Escort',
    95: 'Learn',
    96: 'Communicate',
    97: 'Depart',
    98: 'Search',
    99: 'Charge',
    100: 'Summon'}
# Table which you can use to answer questions or generate new situations.
# Combined, the Action and Theme tables provide creative prompts suitable for
# most situations and questions.
theme_ironsworn = {
    1: 'Risk',
    2: 'Ability',
    3: 'Price',
    4: 'Ally',
    5: 'Battle',
    6: 'Safety',
    7: 'Survival',
    8: 'Weapon',
    9: 'Wound',
    10: 'Shelter',
    11: 'Leader',
    12: 'Fear',
    13: 'Time',
    14: 'Duty',
    15: 'Secret',
    16: 'Innocence',
    17: 'Renown',
    18: 'Direction',
    19: 'Death',
    20: 'Honor',
    21: 'Labor',
    22: 'Solution',
    23: 'Tool',
    24: 'Balance',
    25: 'Love',
    26: 'Barrier',
    27: 'Creation',
    28: 'Decay',
    29: 'Trade',
    30: 'Bond',
    31: 'Hope',
    32: 'Superstition',
    33: 'Peace',
    34: 'Deception',
    35: 'History',
    36: 'World',
    37: 'Vow',
    38: 'Protection',
    39: 'Nature',
    40: 'Opinion',
    41: 'Burden',
    42: 'Vengeance',
    43: 'Opportunity',
    44: 'Faction',
    45: 'Danger',
    46: 'Corruption',
    47: 'Freedom',
    48: 'Debt',
    49: 'Hate',
    50: 'Possession',
    51: 'Stranger',
    52: 'Passage',
    53: 'Land',
    54: 'Creature',
    55: 'Disease',
    56: 'Advantage',
    57: 'Blood',
    58: 'Language',
    59: 'Rumor',
    60: 'Weakness',
    61: 'Greed',
    62: 'Family',
    63: 'Resource',
    64: 'Structure',
    65: 'Dream',
    66: 'Community',
    67: 'War',
    68: 'Portent',
    69: 'Prize',
    70: 'Destiny',
    71: 'Momentum',
    72: 'Power',
    73: 'Memory',
    74: 'Ruin',
    75: 'Mysticism',
    76: 'Rival',
    77: 'Problem',
    78: 'Idea',
    79: 'Revenge',
    80: 'Health',
    81: 'Fellowship',
    82: 'Enemy',
    83: 'Religion',
    84: 'Spirit',
    85: 'Fame',
    86: 'Desolation',
    87: 'Strength',
    88: 'Knowledge',
    89: 'Truth',
    90: 'Quest',
    91: 'Pride',
    92: 'Loss',
    93: 'Law',
    94: 'Path',
    95: 'Warning',
    96: 'Relationship',
    97: 'Wealth',
    98: 'Home',
    99: 'Strategy',
    100: 'Supply'}
# Use this oracle when traveling to generate a point-of-interest or to answer a
# question about a place where someone or something can be found.
location_ironsworn = {
    1: 'Hideout',
    2: 'Ruin',
    3: 'Mine',
    4: 'Waste',
    5: 'Mystical Site',
    6: 'Path',
    7: 'Outpost',
    8: 'Wall',
    9: 'Battlefield',
    10: 'Hovel',
    11: 'Spring',
    12: 'Lair',
    13: 'Fort',
    14: 'Bridge',
    15: 'Camp',
    16: 'Cairn/Grave',
    17: 'Caravan',
    18: 'Caravan',
    19: 'Waterfall',
    20: 'Waterfall',
    21: 'Cave',
    22: 'Cave',
    23: 'Swamp',
    24: 'Swamp',
    25: 'Fen',
    26: 'Fen',
    27: 'Ravine',
    28: 'Ravine',
    29: 'Road',
    30: 'Road',
    31: 'Tree',
    32: 'Tree',
    33: 'Pond',
    34: 'Pond',
    35: 'Fields',
    36: 'Fields',
    37: 'Marsh',
    38: 'Marsh',
    39: 'Steading',
    40: 'Steading',
    41: 'Rapids',
    42: 'Rapids',
    43: 'Pass',
    44: 'Pass',
    45: 'Trail',
    46: 'Trail',
    47: 'Glade',
    48: 'Glade',
    49: 'Plain',
    50: 'Plain',
    51: 'Ridge',
    52: 'Ridge',
    53: 'Cliff',
    54: 'Cliff',
    55: 'Grove',
    56: 'Grove',
    57: 'Village',
    58: 'Village',
    59: 'Moor',
    60: 'Moor',
    61: 'Thicket',
    62: 'Thicket',
    63: 'River Ford',
    64: 'River Ford',
    65: 'Valley',
    66: 'Valley',
    67: 'Bay/Fjord',
    68: 'Bay/Fjord',
    69: 'Foothills',
    70: 'Foothills',
    71: 'Lake',
    72: 'Lake',
    73: 'River',
    74: 'River',
    75: 'River',
    76: 'Forest',
    77: 'Forest',
    78: 'Forest',
    79: 'Forest',
    80: 'Coast',
    81: 'Coast',
    82: 'Coast',
    83: 'Coast',
    84: 'Hill',
    85: 'Hill',
    86: 'Hill',
    87: 'Hill',
    88: 'Hill',
    89: 'Mountain',
    90: 'Mountain',
    91: 'Mountain',
    92: 'Mountain',
    93: 'Mountain',
    94: 'Woods',
    95: 'Woods',
    96: 'Woods',
    97: 'Woods',
    98: 'Woods',
    99: 'Woods',
    100: 'Anomaly'}
# Use this oracle to identify a point-of-interest or destination when you are
# traveling by ship or boat along the coast.
coastal_waters_locations_ironsworn = {
    1: 'Fleet',
    2: 'Sargassum',
    3: 'Flotsam',
    4: 'Mystical Site',
    5: 'Lair',
    6: 'Wreck',
    7: 'Wreck',
    8: 'Wreck',
    9: 'Wreck',
    10: 'Wreck',
    11: 'Harbor',
    12: 'Harbor',
    13: 'Harbor',
    14: 'Harbor',
    15: 'Harbor',
    16: 'Ship',
    17: 'Ship',
    18: 'Ship',
    19: 'Ship',
    20: 'Ship',
    21: 'Ship',
    22: 'Ship',
    23: 'Ship',
    24: 'Rocks',
    25: 'Rocks',
    26: 'Rocks',
    27: 'Rocks',
    28: 'Rocks',
    29: 'Rocks',
    30: 'Rocks',
    31: 'Fjord',
    32: 'Fjord',
    33: 'Fjord',
    34: 'Fjord',
    35: 'Fjord',
    36: 'Fjord',
    37: 'Fjord',
    38: 'Fjord',
    39: 'Estuary',
    40: 'Estuary',
    41: 'Estuary',
    42: 'Estuary',
    43: 'Estuary',
    44: 'Estuary',
    45: 'Estuary',
    46: 'Estuary',
    47: 'Cove',
    48: 'Cove',
    49: 'Cove',
    50: 'Cove',
    51: 'Cove',
    52: 'Cove',
    53: 'Cove',
    54: 'Cove',
    55: 'Bay',
    56: 'Bay',
    57: 'Bay',
    58: 'Bay',
    59: 'Bay',
    60: 'Bay',
    61: 'Bay',
    62: 'Bay',
    63: 'Ice',
    64: 'Ice',
    65: 'Ice',
    66: 'Ice',
    67: 'Ice',
    68: 'Ice',
    69: 'Ice',
    70: 'Ice',
    71: 'Island',
    72: 'Island',
    73: 'Island',
    74: 'Island',
    75: 'Island',
    76: 'Island',
    77: 'Island',
    78: 'Island',
    79: 'Island',
    80: 'Island',
    81: 'Island',
    82: 'Island',
    83: 'Island',
    84: 'Island',
    85: 'Island',
    86: 'Open Water',
    87: 'Open Water',
    88: 'Open Water',
    89: 'Open Water',
    90: 'Open Water',
    91: 'Open Water',
    92: 'Open Water',
    93: 'Open Water',
    94: 'Open Water',
    95: 'Open Water',
    96: 'Open Water',
    97: 'Open Water',
    98: 'Open Water',
    99: 'Open Water',
    100: 'Anomaly'}
# Use this oracle to add detail to the Location or Coastal Waters Location
# oracles, or by itself to generate a description of a location. Roll more than
# once for extra detail.
location_descriptor_ironsworn = {
    1: 'High',
    2: 'High',
    3: 'Remote',
    4: 'Remote',
    5: 'Exposed',
    6: 'Exposed',
    7: 'Small',
    8: 'Small',
    9: 'Broken',
    10: 'Broken',
    11: 'Diverse',
    12: 'Diverse',
    13: 'Rough',
    14: 'Rough',
    15: 'Dark',
    16: 'Dark',
    17: 'Shadowy',
    18: 'Shadowy',
    19: 'Contested',
    20: 'Contested',
    21: 'Grim',
    22: 'Grim',
    23: 'Wild',
    24: 'Wild',
    25: 'Fertile',
    26: 'Fertile',
    27: 'Blocked',
    28: 'Blocked',
    29: 'Ancient',
    30: 'Ancient',
    31: 'Perilous',
    32: 'Perilous',
    33: 'Hidden',
    34: 'Hidden',
    35: 'Occupied',
    36: 'Occupied',
    37: 'Rich',
    38: 'Rich',
    39: 'Big',
    40: 'Big',
    41: 'Savage',
    42: 'Savage',
    43: 'Defended',
    44: 'Defended',
    45: 'Withered',
    46: 'Withered',
    47: 'Mystical',
    48: 'Mystical',
    49: 'Inaccessible',
    50: 'Inaccessible',
    51: 'Protected',
    52: 'Protected',
    53: 'Abandoned',
    54: 'Abandoned',
    55: 'Wide',
    56: 'Wide',
    57: 'Foul',
    58: 'Foul',
    59: 'Dead',
    60: 'Dead',
    61: 'Ruined',
    62: 'Ruined',
    63: 'Barren',
    64: 'Barren',
    65: 'Cold',
    66: 'Cold',
    67: 'Blighted',
    68: 'Blighted',
    69: 'Low',
    70: 'Low',
    71: 'Beautiful',
    72: 'Beautiful',
    73: 'Abundant',
    74: 'Abundant',
    75: 'Lush',
    76: 'Lush',
    77: 'Flooded',
    78: 'Flooded',
    79: 'Empty',
    80: 'Empty',
    81: 'Strange',
    82: 'Strange',
    83: 'Corrupted',
    84: 'Corrupted',
    85: 'Peaceful',
    86: 'Peaceful',
    87: 'Forgotten',
    88: 'Forgotten',
    89: 'Expansive',
    90: 'Expansive',
    91: 'Settled',
    92: 'Settled',
    93: 'Dense',
    94: 'Dense',
    95: 'Civilized',
    96: 'Civilized',
    97: 'Desolate',
    98: 'Desolate',
    99: 'Isolated',
    100: 'Isolated'}
# Use this table to generate a narrative hook for a problem faced by a community.
# This oracle can help inspire a vow for your character or serve as a prompt for a
# trouble you encounter when you interact with a settlement. Use other oracles,
# as appropriate, to help flesh out the answer.
settlement_trouble_ironsworn = {
    1: 'Outsiders rejected',
    2: 'Outsiders rejected',
    3: 'Dangerous discovery',
    4: 'Dangerous discovery',
    5: 'Dreadful omens',
    6: 'Dreadful omens',
    7: 'Natural disaster',
    8: 'Natural disaster',
    9: 'Old wounds reopened',
    10: 'Old wounds reopened',
    11: 'Important object is lost',
    12: 'Important object is lost',
    13: 'Someone is captured',
    14: 'Someone is captured',
    15: 'Mysterious phenomenon',
    16: 'Mysterious phenomenon',
    17: 'Revolt against a leader',
    18: 'Revolt against a leader',
    19: 'Vengeful outcast',
    20: 'Vengeful outcast',
    21: 'Rival settlement',
    22: 'Rival settlement',
    23: 'Nature strikes back',
    24: 'Nature strikes back',
    25: 'Someone is missing',
    26: 'Someone is missing',
    27: 'Production halts',
    28: 'Production halts',
    29: 'Mysterious murders',
    30: 'Mysterious murders',
    31: 'Debt comes due',
    32: 'Debt comes due',
    33: 'Unjust leadership',
    34: 'Unjust leadership',
    35: 'Disastrous accident',
    36: 'Disastrous accident',
    37: 'In league with the enemy',
    38: 'In league with the enemy',
    39: 'Raiders prey on the weak',
    40: 'Raiders prey on the weak',
    41: 'Cursed past',
    42: 'Cursed past',
    43: 'An innocent is accused',
    44: 'An innocent is accused',
    45: 'Corrupted by dark magic',
    46: 'Corrupted by dark magic',
    47: 'Isolated by brutal weather',
    48: 'Isolated by brutal weather',
    49: 'Provisions are scarce',
    50: 'Provisions are scarce',
    51: 'Sickness run amok',
    52: 'Sickness run amok',
    53: 'Allies become enemies',
    54: 'Allies become enemies',
    55: 'Attack is imminent',
    56: 'Attack is imminent',
    57: 'Lost caravan',
    58: 'Lost caravan',
    59: 'Dark secret revealed',
    60: 'Dark secret revealed',
    61: 'Urgent expedition',
    62: 'Urgent expedition',
    63: 'A leader falls',
    64: 'A leader falls',
    65: 'Families in conflict',
    66: 'Families in conflict',
    67: 'Incompetent leadership',
    68: 'Incompetent leadership',
    69: 'Reckless warmongering',
    70: 'Reckless warmongering',
    71: 'Beast on the hunt',
    72: 'Beast on the hunt',
    73: 'Betrayed from within',
    74: 'Betrayed from within',
    75: 'Broken truce',
    76: 'Broken truce',
    77: 'Wrathful haunt',
    78: 'Wrathful haunt',
    79: 'Conflict with firstborn',
    80: 'Conflict with firstborn',
    81: 'Trade route blocked',
    82: 'Trade route blocked',
    83: 'In the crossfire',
    84: 'In the crossfire',
    85: 'Stranger causes discord',
    86: 'Stranger causes discord',
    87: 'Important event threatened',
    88: 'Important event threatened',
    89: 'Dangerous tradition',
    90: 'Dangerous tradition',
    91: 'Roll twice',
    92: 'Roll twice',
    93: 'Roll twice',
    94: 'Roll twice',
    95: 'Roll twice',
    96: 'Roll twice',
    97: 'Roll twice',
    98: 'Roll twice',
    99: 'Roll twice',
    100: 'Roll twice'}
# Use this oracle to define the background for a character, or to generate a
# random encounter.
character_role_ironsworn = {
    1: 'Criminal',
    2: 'Criminal',
    3: 'Healer',
    4: 'Healer',
    5: 'Bandit',
    6: 'Bandit',
    7: 'Guide',
    8: 'Guide',
    9: 'Guide',
    10: 'Performer',
    11: 'Performer',
    12: 'Performer',
    13: 'Miner',
    14: 'Miner',
    15: 'Miner',
    16: 'Mercenary',
    17: 'Mercenary',
    18: 'Mercenary',
    19: 'Outcast',
    20: 'Outcast',
    21: 'Outcast',
    22: 'Vagrant',
    23: 'Vagrant',
    24: 'Vagrant',
    25: 'Forester',
    26: 'Forester',
    27: 'Forester',
    28: 'Traveler',
    29: 'Traveler',
    30: 'Traveler',
    31: 'Mystic',
    32: 'Mystic',
    33: 'Mystic',
    34: 'Priest',
    35: 'Priest',
    36: 'Priest',
    37: 'Sailor',
    38: 'Sailor',
    39: 'Sailor',
    40: 'Pilgrim',
    41: 'Pilgrim',
    42: 'Pilgrim',
    43: 'Thief',
    44: 'Thief',
    45: 'Thief',
    46: 'Adventurer',
    47: 'Adventurer',
    48: 'Adventurer',
    49: 'Forager',
    50: 'Forager',
    51: 'Forager',
    52: 'Leader',
    53: 'Leader',
    54: 'Leader',
    55: 'Guard',
    56: 'Guard',
    57: 'Guard',
    58: 'Guard',
    59: 'Artisan',
    60: 'Artisan',
    61: 'Artisan',
    62: 'Artisan',
    63: 'Scout',
    64: 'Scout',
    65: 'Scout',
    66: 'Scout',
    67: 'Herder',
    68: 'Herder',
    69: 'Herder',
    70: 'Herder',
    71: 'Fisher',
    72: 'Fisher',
    73: 'Fisher',
    74: 'Fisher',
    75: 'Warrior',
    76: 'Warrior',
    77: 'Warrior',
    78: 'Warrior',
    79: 'Warrior',
    80: 'Hunter',
    81: 'Hunter',
    82: 'Hunter',
    83: 'Hunter',
    84: 'Hunter',
    85: 'Raider',
    86: 'Raider',
    87: 'Raider',
    88: 'Raider',
    89: 'Raider',
    90: 'Trader',
    91: 'Trader',
    92: 'Trader',
    93: 'Trader',
    94: 'Trader',
    95: 'Farmer',
    96: 'Farmer',
    97: 'Farmer',
    98: 'Farmer',
    99: 'Farmer',
    100: 'Unusual role'}
# Use this oracle to define the primary motivation of an NPC or a faction. It can
# also be used to kick off a personal quest for your own character
character_goal_ironsworn = {
    1: 'Obtain an object',
    2: 'Obtain an object',
    3: 'Obtain an object',
    4: 'Make an agreement',
    5: 'Make an agreement',
    6: 'Make an agreement',
    7: 'Build a relationship',
    8: 'Build a relationship',
    9: 'Build a relationship',
    10: 'Undermine a relationship',
    11: 'Undermine a relationship',
    12: 'Undermine a relationship',
    13: 'Seek a truth',
    14: 'Seek a truth',
    15: 'Seek a truth',
    16: 'Pay a debt',
    17: 'Pay a debt',
    18: 'Pay a debt',
    19: 'Refute a falsehood',
    20: 'Refute a falsehood',
    21: 'Refute a falsehood',
    22: 'Harm a rival',
    23: 'Harm a rival',
    24: 'Harm a rival',
    25: 'Cure an ill',
    26: 'Cure an ill',
    27: 'Cure an ill',
    28: 'Find a person',
    29: 'Find a person',
    30: 'Find a person',
    31: 'Find a home',
    32: 'Find a home',
    33: 'Find a home',
    34: 'Seize power',
    35: 'Seize power',
    36: 'Seize power',
    37: 'Restore a relationship',
    38: 'Restore a relationship',
    39: 'Restore a relationship',
    40: 'Create an item',
    41: 'Create an item',
    42: 'Create an item',
    43: 'Travel to a place',
    44: 'Travel to a place',
    45: 'Travel to a place',
    46: 'Secure provisions',
    47: 'Secure provisions',
    48: 'Secure provisions',
    49: 'Rebel against power',
    50: 'Rebel against power',
    51: 'Rebel against power',
    52: 'Collect a debt',
    53: 'Collect a debt',
    54: 'Collect a debt',
    55: 'Protect a secret',
    56: 'Protect a secret',
    57: 'Protect a secret',
    58: 'Spread faith',
    59: 'Spread faith',
    60: 'Spread faith',
    61: 'Enrich themselves',
    62: 'Enrich themselves',
    63: 'Enrich themselves',
    64: 'Protect a person',
    65: 'Protect a person',
    66: 'Protect a person',
    67: 'Protect the status quo',
    68: 'Protect the status quo',
    69: 'Protect the status quo',
    70: 'Advance status',
    71: 'Advance status',
    72: 'Advance status',
    73: 'Defend a place',
    74: 'Defend a place',
    75: 'Defend a place',
    76: 'Avenge a wrong',
    77: 'Avenge a wrong',
    78: 'Avenge a wrong',
    79: 'Fulfill a duty',
    80: 'Fulfill a duty',
    81: 'Fulfill a duty',
    82: 'Gain knowledge',
    83: 'Gain knowledge',
    84: 'Gain knowledge',
    85: 'Prove worthiness',
    86: 'Prove worthiness',
    87: 'Prove worthiness',
    88: 'Find redemption',
    89: 'Find redemption',
    90: 'Find redemption',
    91: 'Escape from something',
    92: 'Escape from something',
    93: 'Resolve a dispute',
    94: 'Resolve a dispute',
    95: 'Resolve a dispute',
    96: 'Roll twice',
    97: 'Roll twice',
    98: 'Roll twice',
    99: 'Roll twice',
    100: 'Roll twice'}
# Use this oracle to help flesh out a character’s personality or physical
# characteristics. Roll more than once to add additional detail. You can combine
# all three character oracles (role, goal and descriptor), plus a roll on an appropriate name
# table, to build an outline of an NPC.
character_descriptor_ironsworn = {
    1: 'Stoic',
    2: 'Attractive',
    3: 'Passive',
    4: 'Aloof',
    5: 'Affectionate',
    6: 'Generous',
    7: 'Smug',
    8: 'Armed',
    9: 'Clever',
    10: 'Brave',
    11: 'Ugly',
    12: 'Sociable',
    13: 'Doomed',
    14: 'Connected',
    15: 'Bold',
    16: 'Jealous',
    17: 'Angry',
    18: 'Active',
    19: 'Suspicious',
    20: 'Hostile',
    21: 'Hardhearted',
    22: 'Successful',
    23: 'Talented',
    24: 'Experienced',
    25: 'Deceitful',
    26: 'Ambitious',
    27: 'Aggressive',
    28: 'Conceited',
    29: 'Proud',
    30: 'Stern',
    31: 'Dependent',
    32: 'Wary',
    33: 'Strong',
    34: 'Insightful',
    35: 'Dangerous',
    36: 'Quirky',
    37: 'Cheery',
    38: 'Disfigured',
    39: 'Intolerant',
    40: 'Skilled',
    41: 'Stingy',
    42: 'Timid',
    43: 'Insensitive',
    44: 'Wild',
    45: 'Bitter',
    46: 'Cunning',
    47: 'Remorseful',
    48: 'Kind',
    49: 'Charming',
    50: 'Oblivious',
    51: 'Critical',
    52: 'Cautious',
    53: 'Resourceful',
    54: 'Weary',
    55: 'Wounded',
    56: 'Anxious',
    57: 'Powerful',
    58: 'Athletic',
    59: 'Driven',
    60: 'Cruel',
    61: 'Quiet',
    62: 'Honest',
    63: 'Infamous',
    64: 'Dying',
    65: 'Reclusive',
    66: 'Artistic',
    67: 'Disabled',
    68: 'Confused',
    69: 'Manipulative',
    70: 'Relaxed',
    71: 'Stealthy',
    72: 'Confident',
    73: 'Weak',
    74: 'Friendly',
    75: 'Wise',
    76: 'Influential',
    77: 'Young',
    78: 'Adventurous',
    79: 'Oppressed',
    80: 'Vengeful',
    81: 'Cooperative',
    82: 'Armored',
    83: 'Apathetic',
    84: 'Determined',
    85: 'Loyal',
    86: 'Sick',
    87: 'Religious',
    88: 'Selfish',
    89: 'Old',
    90: 'Fervent',
    91: 'Violent',
    92: 'Agreeable',
    93: 'Hot-tempered',
    94: 'Stubborn',
    95: 'Incompetent',
    96: 'Greedy',
    97: 'Cowardly',
    98: 'Obsessed',
    99: 'Careless',
    100: 'Ironsworn'}
# Use this oracle to help inspire an action for an NPC in combat. When you’re
# not sure what your foe does next, particularly when they have initiative,
combat_action_ironsworn = {
    1: 'Compel a surrender.',
    2: 'Compel a surrender.',
    3: 'Compel a surrender.',
    4: 'Coordinate with allies.',
    5: 'Coordinate with allies.',
    6: 'Coordinate with allies.',
    7: 'Gather reinforcements.',
    8: 'Gather reinforcements.',
    9: 'Gather reinforcements.',
    10: 'Seize something or someone.',
    11: 'Seize something or someone.',
    12: 'Seize something or someone.',
    13: 'Seize something or someone.',
    14: 'Provoke a reckless response.',
    15: 'Provoke a reckless response.',
    16: 'Provoke a reckless response.',
    17: 'Provoke a reckless response.',
    18: 'Intimidate or frighten.',
    19: 'Intimidate or frighten.',
    20: 'Intimidate or frighten.',
    21: 'Intimidate or frighten.',
    22: 'Reveal a surprising truth.',
    23: 'Reveal a surprising truth.',
    24: 'Reveal a surprising truth.',
    25: 'Reveal a surprising truth.',
    26: 'Shift focus to someone or something else.',
    27: 'Shift focus to someone or something else.',
    28: 'Shift focus to someone or something else.',
    29: 'Shift focus to someone or something else.',
    30: 'Destroy something, or render it useless.',
    31: 'Destroy something, or render it useless.',
    32: 'Destroy something, or render it useless.',
    33: 'Destroy something, or render it useless.',
    34: 'Take a decisive action.',
    35: 'Take a decisive action.',
    36: 'Take a decisive action.',
    37: 'Take a decisive action.',
    38: 'Take a decisive action.',
    39: 'Take a decisive action.',
    40: 'Reinforce defenses.',
    41: 'Reinforce defenses.',
    42: 'Reinforce defenses.',
    43: 'Reinforce defenses.',
    44: 'Reinforce defenses.',
    45: 'Reinforce defenses.',
    46: 'Ready an action.',
    47: 'Ready an action.',
    48: 'Ready an action.',
    49: 'Ready an action.',
    50: 'Ready an action.',
    51: 'Ready an action.',
    52: 'Ready an action.',
    53: 'Use the terrain to gain advantage.',
    54: 'Use the terrain to gain advantage.',
    55: 'Use the terrain to gain advantage.',
    56: 'Use the terrain to gain advantage.',
    57: 'Use the terrain to gain advantage.',
    58: 'Use the terrain to gain advantage.',
    59: 'Use the terrain to gain advantage.',
    60: 'Use the terrain to gain advantage.',
    61: 'Leverage the advantage of a weapon or ability.',
    62: 'Leverage the advantage of a weapon or ability.',
    63: 'Leverage the advantage of a weapon or ability.',
    64: 'Leverage the advantage of a weapon or ability.',
    65: 'Leverage the advantage of a weapon or ability.',
    66: 'Leverage the advantage of a weapon or ability.',
    67: 'Leverage the advantage of a weapon or ability.',
    68: 'Leverage the advantage of a weapon or ability.',
    69: 'Create an opportunity.',
    70: 'Create an opportunity.',
    71: 'Create an opportunity.',
    72: 'Create an opportunity.',
    73: 'Create an opportunity.',
    74: 'Create an opportunity.',
    75: 'Create an opportunity.',
    76: 'Create an opportunity.',
    77: 'Create an opportunity.',
    78: 'Create an opportunity.',
    79: 'Attack with precision.',
    80: 'Attack with precision.',
    81: 'Attack with precision.',
    82: 'Attack with precision.',
    83: 'Attack with precision.',
    84: 'Attack with precision.',
    85: 'Attack with precision.',
    86: 'Attack with precision.',
    87: 'Attack with precision.',
    88: 'Attack with precision.',
    89: 'Attack with precision.',
    90: 'Attack with power.',
    91: 'Attack with power.',
    92: 'Attack with power.',
    93: 'Attack with power.',
    94: 'Attack with power.',
    95: 'Attack with power.',
    96: 'Attack with power.',
    97: 'Attack with power.',
    98: 'Attack with power.',
    99: 'Attack with power.',
    100: 'Take a completely unexpected action.'}
# Those who deal in magic may find themselves at the mercy of chaos. This
# oracle can supplement, or replace, the Pay the Price table when
# resolving the outcome of a failed ritual or other negative interaction with
# mystical forces. Use this oracle in dramatic moments, or to introduce an
# unexpected outcome triggered by a match.
mystic_backlash_ironsworn = {
    1: 'Your ritual has the opposite affect.',
    2: 'Your ritual has the opposite affect.',
    3: 'Your ritual has the opposite affect.',
    4: 'Your ritual has the opposite affect.',
    5: 'You are sapped of strength.',
    6: 'You are sapped of strength.',
    7: 'You are sapped of strength.',
    8: 'You are sapped of strength.',
    9: 'Your friend, ally, or companion is adversely affected.',
    10: 'Your friend, ally, or companion is adversely affected.',
    11: 'Your friend, ally, or companion is adversely affected.',
    12: 'Your friend, ally, or companion is adversely affected.',
    13: 'You destroy an important object.',
    14: 'You destroy an important object.',
    15: 'You destroy an important object.',
    16: 'You destroy an important object.',
    17: 'You inadvertently summon a horror.',
    18: 'You inadvertently summon a horror.',
    19: 'You inadvertently summon a horror.',
    20: 'You inadvertently summon a horror.',
    21: 'You collapse, and drift into a troubled sleep.',
    22: 'You collapse, and drift into a troubled sleep.',
    23: 'You collapse, and drift into a troubled sleep.',
    24: 'You collapse, and drift into a troubled sleep.',
    25: 'You undergo a physical torment which leaves its mark upon you.',
    26: 'You undergo a physical torment which leaves its mark upon you.',
    27: 'You undergo a physical torment which leaves its mark upon you.',
    28: 'You undergo a physical torment which leaves its mark upon you.',
    29: 'You hear ghostly voices whispering of dark portents.',
    30: 'You hear ghostly voices whispering of dark portents.',
    31: 'You hear ghostly voices whispering of dark portents.',
    32: 'You hear ghostly voices whispering of dark portents.',
    33: 'You are lost in shadow, and find yourself in another place without memory of how you got there.',
    34: 'You are lost in shadow, and find yourself in another place without memory of how you got there.',
    35: 'You are lost in shadow, and find yourself in another place without memory of how you got there.',
    36: 'You are lost in shadow, and find yourself in another place without memory of how you got there.',
    37: 'You alert someone or something to your presence.',
    38: 'You alert someone or something to your presence.',
    39: 'You alert someone or something to your presence.',
    40: 'You alert someone or something to your presence.',
    41: 'You are not yourself, and act against a friend, ally, or companion.',
    42: 'You are not yourself, and act against a friend, ally, or companion.',
    43: 'You are not yourself, and act against a friend, ally, or companion.',
    44: 'You are not yourself, and act against a friend, ally, or companion.',
    45: 'You affect or damage your surroundings, causing a disturbance or potential harm.',
    46: 'You affect or damage your surroundings, causing a disturbance or potential harm.',
    47: 'You affect or damage your surroundings, causing a disturbance or potential harm.',
    48: 'You affect or damage your surroundings, causing a disturbance or potential harm.',
    49: 'You waste resources.',
    50: 'You waste resources.',
    51: 'You waste resources.',
    52: 'You waste resources.',
    53: 'You suffer the loss of a sense for several hours.',
    54: 'You suffer the loss of a sense for several hours.',
    55: 'You suffer the loss of a sense for several hours.',
    56: 'You suffer the loss of a sense for several hours.',
    57: 'You lose your connection to magic for a day or so, and cannot perform rituals.',
    58: 'You lose your connection to magic for a day or so, and cannot perform rituals.',
    59: 'You lose your connection to magic for a day or so, and cannot perform rituals.',
    60: 'You lose your connection to magic for a day or so, and cannot perform rituals.',
    61: 'Your ritual affects the target in an unexpected and problematic way.',
    62: 'Your ritual affects the target in an unexpected and problematic way.',
    63: 'Your ritual affects the target in an unexpected and problematic way.',
    64: 'Your ritual affects the target in an unexpected and problematic way.',
    65: 'Your ritual reveals a surprising and troubling truth.',
    66: 'Your ritual reveals a surprising and troubling truth.',
    67: 'Your ritual reveals a surprising and troubling truth.',
    68: 'Your ritual reveals a surprising and troubling truth.',
    69: 'You are tempted by dark powers.',
    70: 'You are tempted by dark powers.',
    71: 'You are tempted by dark powers.',
    72: 'You are tempted by dark powers.',
    73: 'You see a troubling vision of your future.',
    74: 'You see a troubling vision of your future.',
    75: 'You see a troubling vision of your future.',
    76: 'You see a troubling vision of your future.',
    77: 'You can not perform this ritual again until you acquire an important component.',
    78: 'You can not perform this ritual again until you acquire an important component.',
    79: 'You can not perform this ritual again until you acquire an important component.',
    80: 'You can not perform this ritual again until you acquire an important component.',
    81: 'You develop a strange fear or compulsion.',
    82: 'You develop a strange fear or compulsion.',
    83: 'You develop a strange fear or compulsion.',
    84: 'You develop a strange fear or compulsion.',
    85: 'Your ritual causes creatures to exhibit strange or aggressive behavior.',
    86: 'Your ritual causes creatures to exhibit strange or aggressive behavior.',
    87: 'Your ritual causes creatures to exhibit strange or aggressive behavior.',
    88: 'Your ritual causes creatures to exhibit strange or aggressive behavior.',
    89: 'You are tormented by an apparition from your past.',
    90: 'You are tormented by an apparition from your past.',
    91: 'You are tormented by an apparition from your past.',
    92: 'You are tormented by an apparition from your past.',
    93: 'You are wracked with sudden sickness.',
    94: 'You are wracked with sudden sickness.',
    95: 'You are wracked with sudden sickness.',
    96: 'You are wracked with sudden sickness.',
    97: 'Roll twice more on this table. Both results occur. If they are the same result, make it worse.',
    98: 'Roll twice more on this table. Both results occur. If they are the same result, make it worse.',
    99: 'Roll twice more on this table. Both results occur. If they are the same result, make it worse.',
    100: 'Roll twice more on this table. Both results occur. If they are the same result, make it worse.'}
# Use the table when you suffer the outcome of a move. 
pay_the_price_ironsworn = {
    1: 'Roll again and apply that result but make it worse. If you roll this result yet again, think of something dreadful that changes the course of your quest (Ask the Oracle if unsure) and make it happen.',
    2: 'Roll again and apply that result but make it worse. If you roll this result yet again, think of something dreadful that changes the course of your quest (Ask the Oracle if unsure) and make it happen.',
    3: 'A person or community you trusted loses faith in you, or acts against you.',
    4: 'A person or community you trusted loses faith in you, or acts against you.',
    5: 'A person or community you trusted loses faith in you, or acts against you.',
    6: 'A person or community you care about is exposed to danger.',
    7: 'A person or community you care about is exposed to danger.',
    8: 'A person or community you care about is exposed to danger.',
    9: 'A person or community you care about is exposed to danger.',
    10: 'You are separated from something or someone.',
    11: 'You are separated from something or someone.',
    12: 'You are separated from something or someone.',
    13: 'You are separated from something or someone.',
    14: 'You are separated from something or someone.',
    15: 'You are separated from something or someone.',
    16: 'You are separated from something or someone.',
    17: 'Your action has an unintended effect.',
    18: 'Your action has an unintended effect.',
    19: 'Your action has an unintended effect.',
    20: 'Your action has an unintended effect.',
    21: 'Your action has an unintended effect.',
    22: 'Your action has an unintended effect.',
    23: 'Your action has an unintended effect.',
    24: 'Something of value is lost or destroyed.',
    25: 'Something of value is lost or destroyed.',
    26: 'Something of value is lost or destroyed.',
    27: 'Something of value is lost or destroyed.',
    28: 'Something of value is lost or destroyed.',
    29: 'Something of value is lost or destroyed.',
    30: 'Something of value is lost or destroyed.',
    31: 'Something of value is lost or destroyed.',
    32: 'Something of value is lost or destroyed.',
    33: 'The current situation worsens.',
    34: 'The current situation worsens.',
    35: 'The current situation worsens.',
    36: 'The current situation worsens.',
    37: 'The current situation worsens.',
    38: 'The current situation worsens.',
    39: 'The current situation worsens.',
    40: 'The current situation worsens.',
    41: 'The current situation worsens.',
    42: 'A new danger or foe is revealed.',
    43: 'A new danger or foe is revealed.',
    44: 'A new danger or foe is revealed.',
    45: 'A new danger or foe is revealed.',
    46: 'A new danger or foe is revealed.',
    47: 'A new danger or foe is revealed.',
    48: 'A new danger or foe is revealed.',
    49: 'A new danger or foe is revealed.',
    50: 'A new danger or foe is revealed.',
    51: 'It causes a delay or puts you at a disadvantage.',
    52: 'It causes a delay or puts you at a disadvantage.',
    53: 'It causes a delay or puts you at a disadvantage.',
    54: 'It causes a delay or puts you at a disadvantage.',
    55: 'It causes a delay or puts you at a disadvantage.',
    56: 'It causes a delay or puts you at a disadvantage.',
    57: 'It causes a delay or puts you at a disadvantage.',
    58: 'It causes a delay or puts you at a disadvantage.',
    59: 'It causes a delay or puts you at a disadvantage.',
    60: 'It is harmful.',
    61: 'It is harmful.',
    62: 'It is harmful.',
    63: 'It is harmful.',
    64: 'It is harmful.',
    65: 'It is harmful.',
    66: 'It is harmful.',
    67: 'It is harmful.',
    68: 'It is harmful.',
    69: 'It is stressful.',
    70: 'It is stressful.',
    71: 'It is stressful.',
    72: 'It is stressful.',
    73: 'It is stressful.',
    74: 'It is stressful.',
    75: 'It is stressful.',
    76: 'It is stressful.',
    77: 'It is stressful.',
    78: 'A surprising development complicates your quest.',
    79: 'A surprising development complicates your quest.',
    80: 'A surprising development complicates your quest.',
    81: 'A surprising development complicates your quest.',
    82: 'A surprising development complicates your quest.',
    83: 'A surprising development complicates your quest.',
    84: 'A surprising development complicates your quest.',
    85: 'A surprising development complicates your quest.',
    86: 'It wastes resources.',
    87: 'It wastes resources.',
    88: 'It wastes resources.',
    89: 'It wastes resources.',
    90: 'It wastes resources.',
    91: 'It forces you to act against your best intentions.',
    92: 'It forces you to act against your best intentions.',
    93: 'It forces you to act against your best intentions.',
    94: 'It forces you to act against your best intentions.',
    95: 'A friend, companion, or ally is put in harm’s way (or you are, if alone).',
    96: 'A friend, companion, or ally is put in harm’s way (or you are, if alone).',
    97: 'A friend, companion, or ally is put in harm’s way (or you are, if alone).',
    98: 'A friend, companion, or ally is put in harm’s way (or you are, if alone).',
    99: 'Roll twice more on this table. Both results occur. If they are the same result, make it worse',
    100: 'Roll twice more on this table. Both results occur. If they are the same result, make it worse'
}
# Use this oracle to introduce a narrative surprise or revelation. Most of these
# results have a negative implication, and can be used to resolve a match at a
# crucial moment in your story.
major_plot_twist_ironsworn = {
    1: 'It was all a diversion.',
    2: 'It was all a diversion.',
    3: 'It was all a diversion.',
    4: 'It was all a diversion.',
    5: 'It was all a diversion.',
    6: 'A dark secret is revealed.',
    7: 'A dark secret is revealed.',
    8: 'A dark secret is revealed.',
    9: 'A dark secret is revealed.',
    10: 'A dark secret is revealed.',
    11: 'A trap is sprung.',
    12: 'A trap is sprung.',
    13: 'A trap is sprung.',
    14: 'A trap is sprung.',
    15: 'A trap is sprung.',
    16: 'An assumption is revealed to be false.',
    17: 'An assumption is revealed to be false.',
    18: 'An assumption is revealed to be false.',
    19: 'An assumption is revealed to be false.',
    20: 'An assumption is revealed to be false.',
    21: 'A secret alliance is revealed.',
    22: 'A secret alliance is revealed.',
    23: 'A secret alliance is revealed.',
    24: 'A secret alliance is revealed.',
    25: 'A secret alliance is revealed.',
    26: 'Your actions benefit an enemy.',
    27: 'Your actions benefit an enemy.',
    28: 'Your actions benefit an enemy.',
    29: 'Your actions benefit an enemy.',
    30: 'Your actions benefit an enemy.',
    31: 'Someone returns unexpectedly.',
    32: 'Someone returns unexpectedly.',
    33: 'Someone returns unexpectedly.',
    34: 'Someone returns unexpectedly.',
    35: 'Someone returns unexpectedly.',
    36: 'A more dangerous foe is revealed.',
    37: 'A more dangerous foe is revealed.',
    38: 'A more dangerous foe is revealed.',
    39: 'A more dangerous foe is revealed.',
    40: 'A more dangerous foe is revealed.',
    41: 'You and an enemy share a common goal.',
    42: 'You and an enemy share a common goal.',
    43: 'You and an enemy share a common goal.',
    44: 'You and an enemy share a common goal.',
    45: 'You and an enemy share a common goal.',
    46: 'A true identity is revealed.',
    47: 'A true identity is revealed.',
    48: 'A true identity is revealed.',
    49: 'A true identity is revealed.',
    50: 'A true identity is revealed.',
    51: 'You are betrayed by someone who was trusted.',
    52: 'You are betrayed by someone who was trusted.',
    53: 'You are betrayed by someone who was trusted.',
    54: 'You are betrayed by someone who was trusted.',
    55: 'You are betrayed by someone who was trusted.',
    56: 'You are too late.',
    57: 'You are too late.',
    58: 'You are too late.',
    59: 'You are too late.',
    60: 'You are too late.',
    61: 'The true enemy is revealed.',
    62: 'The true enemy is revealed.',
    63: 'The true enemy is revealed.',
    64: 'The true enemy is revealed.',
    65: 'The true enemy is revealed.',
    66: 'The enemy gains new allies.',
    67: 'The enemy gains new allies.',
    68: 'The enemy gains new allies.',
    69: 'The enemy gains new allies.',
    70: 'The enemy gains new allies.',
    71: 'A new danger appears.',
    72: 'A new danger appears.',
    73: 'A new danger appears.',
    74: 'A new danger appears.',
    75: 'A new danger appears.',
    76: 'Someone or something goes missing.',
    77: 'Someone or something goes missing.',
    78: 'Someone or something goes missing.',
    79: 'Someone or something goes missing.',
    80: 'Someone or something goes missing.',
    81: 'The truth of a relationship is revealed.',
    82: 'The truth of a relationship is revealed.',
    83: 'The truth of a relationship is revealed.',
    84: 'The truth of a relationship is revealed.',
    85: 'The truth of a relationship is revealed.',
    86: 'Two seemingly unrelated situations are shown to be connected.',
    87: 'Two seemingly unrelated situations are shown to be connected.',
    88: 'Two seemingly unrelated situations are shown to be connected.',
    89: 'Two seemingly unrelated situations are shown to be connected.',
    90: 'Two seemingly unrelated situations are shown to be connected.',
    91: 'Unexpected powers or abilities are revealed.',
    92: 'Unexpected powers or abilities are revealed.',
    93: 'Unexpected powers or abilities are revealed.',
    94: 'Unexpected powers or abilities are revealed.',
    95: 'Unexpected powers or abilities are revealed.',
    96: 'Roll twice more on this table. Both results occur. If they are the same result, make it more dramatic.',
    97: 'Roll twice more on this table. Both results occur. If they are the same result, make it more dramatic.',
    98: 'Roll twice more on this table. Both results occur. If they are the same result, make it more dramatic.',
    99: 'Roll twice more on this table. Both results occur. If they are the same result, make it more dramatic.',
    100: 'Roll twice more on this table. Both results occur. If they are the same result, make it more dramatic.'}
#
# Stonetop
#
# Great Wood
#
terrain_great_wood_stonetop = {
    1: 'Pond, wetland, or lake',
    2: 'Creek, stream, or river',
    3: 'Rocky outcropping, cave(s)',
    4: 'Clearing, meadow, barrens',
    5: 'Clearing, meadow, barrens',
    6: 'Dense thicket',
    7: 'Dense thicket',
    8: 'Swath of one type of tree',
    9: 'Swath of one type of tree',
    10: 'Briars, thorns, nettles',
    11: 'Slope, hill, ridge, ravine',
    12: 'Single, notable tree'}

discovery_great_wood_stonetop = {
    1: 'A change of terrain and roll again',
    2: 'Insight into a danger/threat (numbers, whereabouts, behaviors, strengths, weaknesses, etc.)',
    3: 'Game',
    4: 'Useful or valuable flora',
    5: 'A crinwin, fae or spirit of the wild, curious or indifferent',
    6: 'A point of interest'}

game_great_wood_stonetop = {
    1: 'Mostly harmless but prone to bolt: deer, fowl, rabbits, etc.',
    2: 'Mostly harmless but prone to bolt: deer, fowl, rabbits, etc.',
    3: 'Mostly harmless but prone to bolt: deer, fowl, rabbits, etc.',
    4: 'Big and dangerous if provoked: boars, wisents, tal gerdwyr, etc.',
    5: 'Big and dangerous if provoked: boars, wisents, tal gerdwyr, etc.',
    6: 'Deadly and easily provoked: cave bears, ceirwmawr, raselbaedd, etc.'}

point_of_interest_great_wood_stonetop = {
    1: 'A place corrupted by the Things Below or the Fomoraij',
    2: 'A place haunted by death and the undying',
    3: 'A place bearing traces of the Forest Folk',
    4: 'A place sacred to the spirits of the wild',
    5: 'A fae demesne or waystone ',
    6: 'A ruin or artifact of the Green Lords'}
#
# Green Lords
#
theme_green_lords_stonetop = {
    1: 'Beasts or vermin: bred, changed, or harnessed',
    2: 'Plants and growing things: grandiose and/or unusual',
    3: 'Adaptation/growth/ expansion/vitality',
    4: 'Chimerae: creatures with disparate parts, features of other organisms',
    5: 'Tombs, mummification, constructed afterlives',
    6: 'The spirits of the wild or that which they embody, bound or put to use',
    7: 'Fae  servants/rebellion',
    8: 'Corruption by the Things Below, and roll again',
    9: 'Sized for giants, and roll d8 again',
    10: 'Sized for giants, and roll d8 again',
    11: 'Sized for giants, and roll d8 again',
    12: 'Sized for giants, and roll d8 again', }

site_sites_green_lords_stonetop = {
    1: 'Lingering signs of their presence and influence (at right)',
    2: 'Lingering signs of their presence and influence (at right)',
    3: 'Lingering signs of their presence and influence (at right)',
    4: 'Lingering signs of their presence and influence (at right)',
    5: 'A ruin',
    6: 'A ruin', }

lingering_sites_signs_green_lords_stonetop = {
    1: 'An entity, imprisoned in a strange tree, rune-carved stone, or natural feature',
    2: 'Strange plants ',
    3: 'A section of the Broken Roads, unearthed or still barely visible',
    4: 'A spirit of the wild, bound to some useful purpose',
    5: 'Useful or valuable flora  growing in abundance',
    6: 'A waystone ', }

# Ruins
# Pick or roll for themes (see above), structure, purpose, architectural elements,
# and condition (see below). Place it in an appropriate terrain. Populate it with
# lingering signs, artifacts and/or dangers of the Green Lords or the appropriate region.
structure_ruins_green_lords_stonetop = {
    1: 'Sprawling compound of “smaller” buildings',
    2: 'Single, smaller building',
    3: 'Earth-covered mound',
    4: 'Ancient trees, rooms and structures built into hollows and on crooks',
    5: 'Underground vault(s)',
    6: 'Ziggurat/pyramid/dome', }

purpose_ruins_green_lords_stonetop = {
    1: 'Dwelling (home, barracks, dormitory, etc.)',
    2: 'Containment (fortress, prison, kennel, menagerie, etc.)',
    3: 'Storage (cellar, vault, warehouse, library, collection, etc.)',
    4: 'Production (workshop, nursery, factory, kitchen, abattoir, etc.)',
    5: 'Esoteric (laboratory, shrine, surgery, etc.)',
    6: 'Tomb (of a Green Lord, their ancestors, their servants, their creations, etc.)', }

architectural_elements_ruins_green_lords_stonetop = {
    1: 'Huge slabs of smooth stone (white marble, granite, serpentine) carved with scrollwork and bas reliefs',
    2: 'Moss and lichen, of striking colors, growing in decorative patterns',
    3: 'Amber, agate, geodes, even unworked boulders of interesting shape',
    4: 'Ivory, bone, horn, antler, fur, silk— sometimes fused with or growing from wood or stone',
    5: 'Pillars, arches, or even walls of petrified wood, seemingly grown into shape',
    6: 'Vines and tendrils (often petrified, vitrified, or metal-infused) clinging to surfaces in branching whorls, sigils, and runes', }

condition_ruins_green_lords_stonetop = {
    1: 'Shattered and laid waste by time, war, or vandalism; mostly buried, submerged, and/or overgrown; its purpose unrecognizable',
    2: 'Shattered and laid waste by time, war, or vandalism; mostly buried, submerged, and/or overgrown; its purpose unrecognizable',
    3: 'Crumbling, largely buried, submerged, and/or overgrown',
    4: 'Crumbling, largely buried, submerged, and/or overgrown',
    5: 'Buried, submerged, and/or overgrown, but mostly intact',
    6: 'Fully visible and strangely well-preserved', }
# 
# Chimerae
# The Green Lords meddled wantonly with life, mixing creatures in impossible
# ways to suit need or whim. Some such creatures linger, breeding true or having
# survived for hundreds of years. Pick or roll for purpose, ability, size, and
# composition. Allow purpose, ability, and size to inform the elements of its
# composition, and what traits it has from each element.
purpose_chimerae_green_lords_stonetop = {
    1: 'War/destruction/murder/hunting',
    2: 'War/destruction/murder/hunting',
    3: 'Defense/protection/companionship',
    4: 'Defense/protection/companionship',
    5: 'Experimentation/insight/curiosity',
    6: 'Experimentation/insight/curiosity',
    7: 'Labor/industry/mundane tasks/ convenience',
    8: 'Labor/industry/mundane tasks/ convenience',
    9: 'Something obscure, or very specific',
    10: 'Something obscure, or very specific',
    11: 'Roll d10 twice and combine',
    12: 'Roll d10 twice and combine', }

ability_chimerae_green_lords_stonetop = {
    1: 'Burn/dissolve/destroy/drain',
    2: 'Transform/mutate/change',
    3: 'Control/influence minds or emotions',
    4: 'Wield/produce/ignore elements or energy',
    5: 'Poison/disease/infect',
    6: 'Hide/mimic/disguise',
    7: 'Entangle/trap/engulf/subdue',
    8: 'Attack at range/over an area',
    9: 'Prowess/mobility/speed',
    10: 'Strength/toughness/durability',
    11: 'Roll d10 twice',
    12: 'Roll d10 twice', }

size_chimerae_green_lords_stonetop = {
    1: 'Cat-sized or smaller (tiny)',
    2: 'Cat-sized or smaller (tiny)',
    3: 'Like a human child (small)',
    4: 'Like a human child (small)',
    5: 'Human-sized',
    6: 'Human-sized',
    7: 'Human-sized',
    8: 'Human-sized',
    9: 'Like a horse, a cart, etc. (large)',
    10: 'Like a horse, a cart, etc. (large)',
    11: 'Like a horse, a cart, etc. (large)',
    12: 'Like an elephant, or bigger (huge)', }

composition_chimerae_green_lords_stonetop = {
    1: 'Beast + beast',
    2: 'Beast + beast',
    3: 'Beast + beast',
    4: 'Beast + beast',
    5: 'Beast + plant',
    6: 'Beast + plant',
    7: 'Beast + mineral',
    8: 'Beast + mineral',
    9: 'Beast + roll d8',
    10: 'Beast + roll d8',
    11: 'Beast + roll d8',
    12: 'Person + roll d8', }
#
# Hazardous growth
# Pick or roll for form and peril, possibly rolling the Die of Fate for size/scope/scale.
# Consider adding a useful property as well.
form_hazardous_growth_green_lords_stonetop = {
    1: 'Invisible to the naked eye/spores/dust',
    2: 'Invisible to the naked eye/spores/dust',
    3: 'Mold/moss/lichen/slime',
    4: 'Mold/moss/lichen/slime',
    5: 'Mushrooms/puffballs/stinkhorns/fungus',
    6: 'Mushrooms/puffballs/stinkhorns/fungus',
    7: 'Vines/briars/brambles/shoots',
    8: 'Vines/briars/brambles/shoots',
    9: 'Flowers/plants/ferns/grasses',
    10: 'Flowers/plants/ferns/grasses',
    11: 'Tree(s)/shrubs/bushes/hedges',
    12: 'Tree(s)/shrubs/bushes/hedges', }

peril_hazardous_growth_green_lords_stonetop = {
    1: 'Crushes, strangles, cuts, stabs (possibly animate)',
    2: 'Eats away, dissolves, absorbs (tissue or specific material)',
    3: 'Grows incredibly quickly, overwhelms, ensnares',
    4: 'Infects, colonizes, sickens, changes',
    5: 'Poisons, weakens, subdues',
    6: 'Causes dizziness, hallucinations, delusions',
    7: 'Releases spores/pollen/etc. that irritate, obscure, agitate',
    8: 'Draws attention (via noise, phosphorescence, scent, etc.)',
    9: 'Roll d10 twice and combine',
    10: 'Roll d10 twice and combine',
    11: 'Roll again with d10 but make it weird—elemental, psychic, spiritual, extremely specific, etc.',
    12: 'Roll again with d10 but make it weird—elemental, psychic, spiritual, extremely specific, etc.'}
#
#
#
import random


table = pay_the_price_ironsworn
repeat = 5

for _ in range(repeat):
    print(
        random.choice(
            list(table.items()
                )
            )
        )
