output_file = "links.md"
init_dir = "E:/GreatRepository/Publishing/GitHubRepositories/Knowledge-Repository"
init_dir_offset = 5
external_repo = {
    "Gatsby": "https://github.com/MislavJaksic/Gatsby-Tutorial",
    "Jekyll": "https://github.com/MislavJaksic/Jekyll-Tutorial",
    "ApacheKafka": "https://github.com/MislavJaksic/Kafka-In-Theory-And-Practice",
    "ABAP": "https://github.com/MislavJaksic/SAP-ABAP-Development/tree/master/ABAP",
    "Gradle": "https://github.com/MislavJaksic/Gradle-Tutorial",
    "GraphQL": "https://github.com/MislavJaksic/GraphQL-Tutorial",
    "Flask": "https://github.com/MislavJaksic/Flask-Tutorial",
    "Latex": "https://github.com/MislavJaksic/Latex-Overleaf",
    "DesignPatterns": "https://github.com/MislavJaksic/Design-Patterns",
    "Spring": "https://github.com/MislavJaksic/Spring-Guides-Tutorials",
    "SAP": "https://github.com/MislavJaksic/SAP-ABAP-Development",
    "CollageLabs": "https://github.com/MislavJaksic/College-Labs",
    "Practise": "https://github.com/MislavJaksic/Practise",
    "Maven": "https://github.com/MislavJaksic/Maven-Tutorial",
    "Selenium": "https://github.com/MislavJaksic/Selenium-Tutorial",
}
semiterminal_dir = ["Argo", "Linux", "Java"]
terminal_dir = [
    "Handlebars",
    "GatsbyJS",
    "Jekyll",
    "Selenium",
    "NodeJS",
    "HackTheBox",
    "Google",
    "RubyOnRails",
    "Flask",
    "Electron",
    "DomeneHR",
    "DNSChecker",
    "Ghost",
    "Shiori",
    "RESTFulWebServices",
    "GraphQL",
    "Postman",
    "Grafana",
    "NiFi",
    "OpenShot",
    "OBS",
    "Practise",
    "Asciinema",
    "TableConverter",
    "Scoop",
    "Chocolatey",
    "Notion",
    "Latex",
    "HomeNetworking",
    "CollageLabs",
    "ApacheSpark",
    "ApacheKafka",
    "Wiki",
    "R",
    "Ruby",
    "Python3.x",
    "Lisp",
    "JavaScript",
    "Spring",
    "Haskell",
    "Go",
    "Elm",
    "C++",
    "ABAP",
    "MicroserviceGuide",
    "DesignPatterns",
    "ComputerVision",
    "CodeComplete",
    "CleanCode",
    "Maven",
    "Gradle",
    "Bazel",
    "Ubuntu",
    "Tmux",
    "ShellScripting",
    "MSYS2",
    "Cygwin",
    "PyCharm",
    "IntelliJIDEA",
    "Eclipse",
    "CodeBlocks",
    "SAP",
    "Atom",
    "VMWare",
    "VirtualBox",
    "OpenStack",
    "Guitar",
    "GitLab",
    "GitHub",
    "Git",
    "Keycloak",
    "CloudFlare",
    "Jaeger",
    "Nginx",
    "Netlify",
    "OracleCloud",
    "GoogleCloudPlatform",
    "DigitalOcean",
    "Gunicorn",
    "SSH",
    "Putty",
    "OpenVPN",
    "Prometheus",
    "Portainer",
    "OperatorFramework",
    "OKD",
    "Linkerd",
    "Kubernetes",
    "OpenPolicyAgent",
    "Helm",
    "Harbor",
    "Docker",
    "Concourse",
    "Brigade",
    "Ambassador",
    "Sourcetrail",
    "Jenkins",
    "ArgoCD",
    "Ansible",
    "Vitess",
    "SQLite",
    "Redis",
    "PostgreSQL",
    "MongoDB",
    "Graphite",
    "ApacheHive",
    "ApacheHadoop",
    "GoogleSheets",
    "Elastic",
    "ApacheDruid",
    "LeadershipTheoryAndPractice",
    "Kanban",
    "AgileManifesto",
    "Conventions",
]
